name: Test Action
run-name: ${{ github.actor }} test Gihub action
on: [pull_request]
jobs:
  Test-action:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job is triggered by ${{ github.event_name }}"
      - name: checkout repo
        uses: actions/checkout@v4
      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: install dependencies
        run: npm ci
